import Foundation

/// Controls the verbosity of the system prompt section generated by `SkillCatalog`.
public enum CatalogStyle: Sendable {
    /// One line per skill: `- slug: Name — description`. Backward-compatible default.
    case compact
    /// Multi-line per skill, including `whenToUse`, `argumentHint`, and `allowedTools` when present.
    case detailed
}

/// A compact representation of a set of skills, suitable for injection into LLM system prompts.
public struct SkillCatalog: Sendable {
    /// The skills included in this catalog.
    public let skills: [Skill]

    public init(skills: [Skill]) {
        self.skills = skills
    }

    /// A compact, newline-delimited listing of all skills.
    ///
    /// Format per line: `- {slug}: {name} — {description}`
    ///
    /// Suitable for embedding directly in a system prompt alongside `systemPromptSection()`.
    public var compactListing: String {
        guard !skills.isEmpty else { return "No skills available." }
        return skills
            .map { "- \($0.id): \($0.description)" }
            .joined(separator: "\n")
    }

    /// Structured catalog entries, suitable for JSON encoding.
    public var entries: [CatalogEntry] {
        skills.map {
            CatalogEntry(
                slug: $0.id,
                name: $0.name,
                description: $0.description,
                whenToUse: $0.whenToUse,
                argumentHint: $0.argumentHint,
                aliases: $0.aliases,
                allowedTools: $0.allowedTools
            )
        }
    }

    /// A Markdown section explaining available skills and how to activate them.
    ///
    /// Embed this in the system prompt so the LLM knows which skills exist
    /// and to call `activate_skill` before using one.
    ///
    /// Equivalent to `systemPromptSection(style: .compact)`.
    public func systemPromptSection() -> String {
        systemPromptSection(style: .compact)
    }

    /// A Markdown section explaining available skills and how to activate them.
    ///
    /// - Parameter style: `.compact` (default) renders one line per skill.
    ///   `.detailed` includes `whenToUse`, `argumentHint`, and `allowedTools` when present.
    public func systemPromptSection(style: CatalogStyle) -> String {
        guard !skills.isEmpty else {
            return "## Available Skills\n\nNo skills are currently available."
        }
        let header = """
        ## Available Skills

        You have access to the following agent skills. \
        Call `activate_skill` with a skill slug to load full instructions before using any skill.

        """
        switch style {
        case .compact:
            return header + compactListing
        case .detailed:
            let entries = skills.map { skill -> String in
                var lines = ["- **\(skill.id)**: \(skill.description)"]
                if let wtu = skill.whenToUse {
                    lines.append("  When to use: \(wtu)")
                }
                if let hint = skill.argumentHint {
                    lines.append("  Arguments: \(hint)")
                }
                if !skill.allowedTools.isEmpty {
                    lines.append("  Tools needed: \(skill.allowedTools.joined(separator: ", "))")
                }
                return lines.joined(separator: "\n")
            }.joined(separator: "\n\n")
            return header + entries
        }
    }

    // MARK: - Token Estimation

    /// Estimates the token count for the system prompt section generated at the given style.
    ///
    /// Uses a character-based heuristic (1 token ≈ 4 UTF-16 code units). Suitable for prompt
    /// budgeting decisions — not a guarantee, as tokenization is model-specific.
    public func estimatedTokenCount(style: CatalogStyle = .compact) -> Int {
        let section = systemPromptSection(style: style)
        return max(1, Int(ceil(Double(section.utf16.count) / 4.0)))
    }

    /// Estimates the token contribution of a single skill's frontmatter fields.
    ///
    /// Combines `name`, `description`, and `whenToUse` (when present) using the same
    /// 1-token-per-4-chars heuristic. Useful for building dynamic per-skill prompt budgets.
    public func estimatedFrontmatterTokenCount(for skill: Skill) -> Int {
        let text = [skill.name, skill.description, skill.whenToUse ?? ""]
            .joined(separator: " ")
        return max(1, Int(ceil(Double(text.utf16.count) / 4.0)))
    }
}

/// A single entry in the skill catalog.
public struct CatalogEntry: Sendable, Codable, Equatable {
    public let slug: String
    public let name: String
    public let description: String
    public let whenToUse: String?
    public let argumentHint: String?
    public let aliases: [String]
    public let allowedTools: [String]
}
